phpqa:
  buildDir: report
  ignoredDirs: vendor
  analyzedDirs: src,tests
  execution: parallel
  report: true
  verbose: true
  tools:
    - parallel-lint:0
    - phpmd:0
    - phpcs:0
    - phpmetrics:0
    - phpstan:0
    - phpunit:0
    - security-checker

phpmd:
  standard: phpmd.xml.dist

phpcs:
  standard: phpcs.xml.dist
  ignoreWarnings: false
  reports:
    cli:
      - full

phpstan:
  level: 7
  standard: phpstan.neon

phpunit:
  binary: vendor/bin/phpunit
  config: phpunit.xml.dist
  reports:
    file:
      coverage: [html, clover]
